# Install and init DVC

Prerequisites: 
-  DVC and requirements.txt packages installed (if not - check README.md file for instructions)
-  A project repository is a Git repo

## Install with pip

In [1]:
!pip install dvc==2.0.5

Collecting dvc==2.0.5
  Using cached dvc-2.0.5-py2.py3-none-any.whl (622 kB)
Collecting voluptuous>=0.11.7
  Using cached voluptuous-0.12.1-py3-none-any.whl (29 kB)
Collecting shtab<2,>=1.3.4
  Using cached shtab-1.3.5-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: pyparsing==2.4.7 in ./dvc-venv/lib/python3.8/site-packages (from dvc==2.0.5) (2.4.7)
Collecting fsspec>=0.8.5
  Using cached fsspec-0.8.7-py3-none-any.whl (103 kB)
Collecting grandalf==0.6
  Using cached grandalf-0.6-py3-none-any.whl (31 kB)
Collecting colorama>=0.3.9
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting networkx>=2.1
  Using cached networkx-2.5-py3-none-any.whl (1.6 MB)
Collecting toml>=0.10.1
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting psutil>=5.8.0
  Using cached psutil-5.8.0-cp38-cp38-manylinux2010_x86_64.whl (296 kB)
Collecting diskcache>=5.2.1
  Using cached diskcache-5.2.1-py3-none-any.whl (44 kB)
Processing /home/alex/.cache/pip/wheels/34/2a/24/a490264ae9041fd48f778ff393526572c80bb498ddecb07ea5/configobj-5.0.6-py3-none-any.whl
Processing /home/alex/.cache/pip/wheels/f4/f4/20/d7114a2d97a2e72ce7189a7f63a6fbd2a33ec6ae6010befca5/flufl.lock-3.2-py3-none-any.whl
Requirement already satisfied: setuptools>=34.0.0 in ./dvc-venv/lib/python3.8/site-packages (from dvc==2.0.5) (44.0.0)
Collecting flatten-dict<1,>=0.3.0
  Using cached flatten_dict-0.3.0-py2.py3-none-any.whl (8.2 kB)
Processing /home/alex/.cache/pip/wheels/bc/7d/26/d3e5714967aa183b5c659493fa88daf270295948d0ac277686/pygtrie-2.3.2-py3-none-any.whl
Collecting pyasn1>=0.4.1
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting ply>=3.9
  Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
Collecting tabulate>=0.8.7
  Using cached tabulate-0.8.9-py3-none-any.whl (25 kB)
Processing /home/alex/.cache/pip/wheels/0f/1b/ca/6263a5227f886599039aee3eed13951a6d44a02ee989ed6eb6/dpath-2.0.1-py3-none-any.whl
Collecting shortuuid>=0.5.0
  Using cached shortuuid-1.0.1-py3-none-any.whl (7.5 kB)
Collecting rich>=9.0.0
  Downloading rich-9.13.0-py3-none-any.whl (197 kB)
     |████████████████████████████████| 197 kB 99 kB/s eta 0:00:01
Collecting zc.lockfile>=1.2.1
  Using cached zc.lockfile-2.0-py2.py3-none-any.whl (9.7 kB)
Collecting dulwich>=0.20.20
  Using cached dulwich-0.20.20-cp38-cp38-manylinux2010_x86_64.whl (515 kB)
Requirement already satisfied: packaging>=19.0 in ./dvc-venv/lib/python3.8/site-packages (from dvc==2.0.5) (20.9)
Collecting python-benedict>=0.21.1
  Using cached python_benedict-0.23.2-py3-none-any.whl (39 kB)
Processing /home/alex/.cache/pip/wheels/59/72/23/ea2daa0727a9f7824c0656b73c1f3d8d13f5327729eadb7084/nanotime-0.5.2-py3-none-any.whl
Collecting typing-extensions>=3.7.4
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting tqdm<5,>=4.45.0
  Downloading tqdm-4.59.0-py2.py3-none-any.whl (74 kB)
     |████████████████████████████████| 74 kB 67 kB/s eta 0:00:01
Collecting gitpython>3
  Using cached GitPython-3.1.14-py3-none-any.whl (159 kB)
Collecting requests>=2.22.0
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting jsonpath-ng>=1.5.1
  Using cached jsonpath_ng-1.5.2-py3-none-any.whl (28 kB)
Collecting appdirs>=1.4.3
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting pygit2>=1.5.0
  Using cached pygit2-1.5.0-cp38-cp38-manylinux2014_x86_64.whl (3.1 MB)
Collecting pathspec>=0.6.0
  Using cached pathspec-0.8.1-py2.py3-none-any.whl (28 kB)
Collecting funcy>=1.14
  Using cached funcy-1.15-py2.py3-none-any.whl (32 kB)
Collecting pydot>=1.2.4
  Using cached pydot-1.4.2-py2.py3-none-any.whl (21 kB)
Collecting distro>=1.3.0
  Using cached distro-1.5.0-py2.py3-none-any.whl (18 kB)
Collecting dictdiffer>=0.8.1
  Using cached dictdiffer-0.8.1-py2.py3-none-any.whl (16 kB)
Collecting ruamel.yaml>=0.16.1
  Downloading ruamel.yaml-0.16.13-py2.py3-none-any.whl (111 kB)
     |████████████████████████████████| 111 kB 82 kB/s eta 0:00:01
Processing /home/alex/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4/future-0.18.2-py3-none-any.whl
Requirement already satisfied: decorator>=4.3.0 in ./dvc-venv/lib/python3.8/site-packages (from networkx>=2.1->dvc==2.0.5) (4.4.2)
Requirement already satisfied: six in ./dvc-venv/lib/python3.8/site-packages (from configobj>=5.0.6->dvc==2.0.5) (1.15.0)
Processing /home/alex/.cache/pip/wheels/19/5b/0b/dddeda22ba1ea469543fc509e14c4218d5addb448af7642844/atpublic-2.1.3-py3-none-any.whl
Collecting pathlib2<3.0,>=2.3
  Using cached pathlib2-2.3.5-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in ./dvc-venv/lib/python3.8/site-packages (from rich>=9.0.0->dvc==2.0.5) (2.8.1)
Collecting commonmark<0.10.0,>=0.9.0
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting certifi
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting urllib3>=1.24.1
  Using cached urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
Requirement already satisfied: python-dateutil in ./dvc-venv/lib/python3.8/site-packages (from python-benedict>=0.21.1->dvc==2.0.5) (2.8.1)
Processing /home/alex/.cache/pip/wheels/5c/d4/80/13a4398421dd85abb4320a7d735004241c586525783d002075/ftfy-5.9-py3-none-any.whl
Requirement already satisfied: pyyaml in ./dvc-venv/lib/python3.8/site-packages (from python-benedict>=0.21.1->dvc==2.0.5) (5.4.1)
Collecting python-fsutil
  Using cached python_fsutil-0.4.0-py3-none-any.whl (11 kB)
Processing /home/alex/.cache/pip/wheels/54/5c/c5/d41fbad29097131fe2ed5e06886434f9483015288c14fc711f/mailchecker-4.0.3-py3-none-any.whl
Collecting xmltodict
  Using cached xmltodict-0.12.0-py2.py3-none-any.whl (9.2 kB)
Collecting phonenumbers
  Using cached phonenumbers-8.12.19-py2.py3-none-any.whl (2.6 MB)
Processing /home/alex/.cache/pip/wheels/91/4d/4f/e740a68c215791688c46c4d6251770a570e8dfea91af1acb5c/python_slugify-4.0.1-py2.py3-none-any.whl
Collecting gitdb<5,>=4.0.1
  Using cached gitdb-4.0.5-py3-none-any.whl (63 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Requirement already satisfied: cffi>=1.4.0 in ./dvc-venv/lib/python3.8/site-packages (from pygit2>=1.5.0->dvc==2.0.5) (1.14.5)
Collecting cached-property
  Using cached cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.10"
  Using cached ruamel.yaml.clib-0.2.2-cp38-cp38-manylinux1_x86_64.whl (578 kB)
Requirement already satisfied: wcwidth in ./dvc-venv/lib/python3.8/site-packages (from ftfy; python_version > "2.7"->python-benedict>=0.21.1->dvc==2.0.5) (0.2.5)
Collecting text-unidecode>=1.3
  Using cached text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Collecting smmap<4,>=3.0.1
  Using cached smmap-3.0.5-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: pycparser in ./dvc-venv/lib/python3.8/site-packages (from cffi>=1.4.0->pygit2>=1.5.0->dvc==2.0.5) (2.20)
Installing collected packages: voluptuous, shtab, fsspec, future, grandalf, colorama, networkx, toml, psutil, diskcache, configobj, atpublic, flufl.lock, pathlib2, flatten-dict, pygtrie, pyasn1, ply, tabulate, dpath, shortuuid, typing-extensions, commonmark, rich, zc.lockfile, certifi, urllib3, dulwich, ftfy, chardet, idna, requests, python-fsutil, mailchecker, xmltodict, phonenumbers, text-unidecode, python-slugify, python-benedict, nanotime, tqdm, smmap, gitdb, gitpython, jsonpath-ng, appdirs, cached-property, pygit2, pathspec, funcy, pydot, distro, dictdiffer, ruamel.yaml.clib, ruamel.yaml, dvc
Successfully installed appdirs-1.4.4 atpublic-2.1.3 cached-property-1.5.2 certifi-2020.12.5 chardet-4.0.0 colorama-0.4.4 commonmark-0.9.1 configobj-5.0.6 dictdiffer-0.8.1 diskcache-5.2.1 distro-1.5.0 dpath-2.0.1 dulwich-0.20.20 dvc-2.0.5 flatten-dict-0.3.0 flufl.lock-3.2 fsspec-0.8.7 ftfy-5.9 funcy-1.15 future-0.18.2 gitdb-4.0.5 gitpython-3.1.14 grandalf-0.6 idna-2.10 jsonpath-ng-1.5.2 mailchecker-4.0.3 nanotime-0.5.2 networkx-2.5 pathlib2-2.3.5 pathspec-0.8.1 phonenumbers-8.12.19 ply-3.11 psutil-5.8.0 pyasn1-0.4.8 pydot-1.4.2 pygit2-1.5.0 pygtrie-2.3.2 python-benedict-0.23.2 python-fsutil-0.4.0 python-slugify-4.0.1 requests-2.25.1 rich-9.13.0 ruamel.yaml-0.16.13 ruamel.yaml.clib-0.2.2 shortuuid-1.0.1 shtab-1.3.5 smmap-3.0.5 tabulate-0.8.9 text-unidecode-1.3 toml-0.10.2 tqdm-4.59.0 typing-extensions-3.7.4.3 urllib3-1.26.3 voluptuous-0.12.1 xmltodict-0.12.0 zc.lockfile-2.0

## Checkout branch `experiments`

In [2]:
!git checkout -b experiments

Переключено на новую ветку «experiments»

## Initialize DVC

References: 
- https://dvc.org/doc/get-started/initialize

In [3]:
!dvc init

Initialized DVC repository.

You can now commit the changes to git.

+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|             <https://dvc.org/doc/user-guide/analytics>              |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: <https://dvc.org/doc>
- Get help and share ideas: <https://dvc.org/chat>
- Star us on GitHub: <https://github.com/iterative/dvc>

## Commit changes

In [4]:
%%bash

git add .
git commit -m "Initialize DVC"

[experiments a270f00] Initialize DVC
 11 files changed, 638 insertions(+), 57 deletions(-)
 create mode 100644 .dvc/.gitignore
 create mode 100644 .dvc/config
 create mode 100644 .dvc/plots/confusion.json
 create mode 100644 .dvc/plots/confusion_normalized.json
 create mode 100644 .dvc/plots/default.json
 create mode 100644 .dvc/plots/linear.json
 create mode 100644 .dvc/plots/scatter.json
 create mode 100644 .dvc/plots/smooth.json
 create mode 100644 .dvcignore

## Review Files and Directories created by DVC

In [5]:
!ls -a .dvc

.  ..  config  .gitignore  plots  tmp

In [6]:
!cat .dvc/.gitignore

/config.local
/tmp
/cache

# Quick Tour of DVC features

## Data Versioning

In [7]:
# Get data 

import pandas as pd
from sklearn.datasets import load_iris

data = load_iris(as_frame=True)
list(data.target_names)
data.frame.to_csv('data/iris.csv', index=False)

In [8]:
# Look on data

data.frame.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [9]:
%%bash

du -sh data/*

4,0K	data/iris.csv

## Add file under DVC control

In [17]:
%%bash

dvc add data/iris.csv

To track the changes with git, run:

	git add data/.gitignore data/iris.csv.dvc

In [18]:
!du -sh data/*

4,0K	data/iris.csv
4,0K	data/iris.csv.dvc

In [19]:
!git status -s data/

?? data/.gitignore
?? data/iris.csv.dvc

In [20]:
%%bash

git add .
git commit -m "Add a source dataset"

[experiments 9d48823] Add a source dataset
 4 files changed, 25 insertions(+), 39 deletions(-)
 create mode 100644 data/.gitignore
 create mode 100644 data/iris.csv.dvc

### What is DVC-file?

Data file internals


>    If you take a look at the DVC-file, you will see that only outputs are defined in outs. 
    In this file, only one output is defined. The output contains the data file path in the repository and md5 cache.
    This md5 cache determines a location of the actual content file in DVC cache directory .dvc/cache
    >> Output from DVC-files defines the relationship between the data file path in a repository and the path in a cache directory. See also DVC File Format



(c) dvc.org https://dvc.org/doc/tutorial/define-ml-pipeline

In [21]:
!cat data/iris.csv.dvc

outs:
- md5: 4d301abed5efe50eccda350cde38e0eb
  size: 2777
  path: iris.csv

## Create and Reproduce ML pipelines 

Stages 
- extract features 
- split dataset 
- train 
- evaluate

### Add a pipeline stage with 'dvc stage add'

In [32]:
!dvc stage add \
    -n feature_extraction \
    -d src/featurization.py \
    -d data/iris.csv \
    -o data/iris_featurized.csv \
    python src/featurization.py

Creating 'dvc.yaml'                                                   core>
Adding stage 'feature_extraction' in 'dvc.yaml'

To track the changes with git, run:

	git add dvc.yaml

In [33]:
!cat dvc.yaml

stages:
  feature_extraction:
    cmd: python src/featurization.py
    deps:
    - data/iris.csv
    - src/featurization.py
    outs:
    - data/iris_featurized.csv

### Add split train/test stage

In [34]:
!dvc stage add \
    -n split_dataset \
    -d src/split_dataset.py \
    -d data/iris_featurized.csv \
    -o data/train.csv \
    -o data/test.csv \
    python src/split_dataset.py --test_size 0.4

Adding stage 'split_dataset' in 'dvc.yaml'                            core>

To track the changes with git, run:

	git add dvc.yaml

In [35]:
!cat dvc.yaml

stages:
  feature_extraction:
    cmd: python src/featurization.py
    deps:
    - data/iris.csv
    - src/featurization.py
    outs:
    - data/iris_featurized.csv
  split_dataset:
    cmd: python src/split_dataset.py --test_size 0.4
    deps:
    - data/iris_featurized.csv
    - src/split_dataset.py
    outs:
    - data/test.csv
    - data/train.csv

### Add train stage

In [36]:
!dvc stage add \
    -n train \
    -d src/train.py \
    -d data/train.csv \
    -o data/model.joblib \
    python src/train.py

Adding stage 'train' in 'dvc.yaml'                                    core>

To track the changes with git, run:

	git add dvc.yaml

In [37]:
!cat dvc.yaml

stages:
  feature_extraction:
    cmd: python src/featurization.py
    deps:
    - data/iris.csv
    - src/featurization.py
    outs:
    - data/iris_featurized.csv
  split_dataset:
    cmd: python src/split_dataset.py --test_size 0.4
    deps:
    - data/iris_featurized.csv
    - src/split_dataset.py
    outs:
    - data/test.csv
    - data/train.csv
  train:
    cmd: python src/train.py
    deps:
    - data/train.csv
    - src/train.py
    outs:
    - data/model.joblib

### Add evaluate stage

In [38]:
!dvc stage add \
    -n evaluate \
    -d src/train.py \
    -d src/evaluate.py \
    -d data/test.csv \
    -d data/model.joblib \
    -m data/eval.txt \
    python src/evaluate.py

Adding stage 'evaluate' in 'dvc.yaml'                                 core>

To track the changes with git, run:

	git add data/.gitignore dvc.yaml

In [39]:
!cat dvc.yaml

stages:
  feature_extraction:
    cmd: python src/featurization.py
    deps:
    - data/iris.csv
    - src/featurization.py
    outs:
    - data/iris_featurized.csv
  split_dataset:
    cmd: python src/split_dataset.py --test_size 0.4
    deps:
    - data/iris_featurized.csv
    - src/split_dataset.py
    outs:
    - data/test.csv
    - data/train.csv
  train:
    cmd: python src/train.py
    deps:
    - data/train.csv
    - src/train.py
    outs:
    - data/model.joblib
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/model.joblib
    - data/test.csv
    - src/evaluate.py
    - src/train.py
    metrics:
    - data/eval.txt

### Run DVC pipeline (all stages)

In [42]:
!dvc repro

'data/iris.csv.dvc' didn't change, skipping                           core>
Running stage 'feature_extraction':
> python src/featurization.py
Generating lock file 'dvc.lock'
Updating lock file 'dvc.lock'

Running stage 'split_dataset':
> python src/split_dataset.py --test_size 0.4
Updating lock file 'dvc.lock'                                         core>

Running stage 'train':
> python src/train.py
Updating lock file 'dvc.lock'                                         core>

Running stage 'evaluate':
> python src/evaluate.py
Updating lock file 'dvc.lock'                                         core>

To track the changes with git, run:

	git add dvc.lock
Use `dvc push` to send your updates to remote storage.

In [43]:
!ls

data			 dvc.lock  dvc.yaml   requirements.txt
dvc-1-get-started.ipynb  dvc-venv  README.md  src

In [44]:
import pandas as pd

features = pd.read_csv('data/iris_featurized.csv')
features.head()

   sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [45]:
!git status -s

 M data/.gitignore
 M dvc-1-get-started.ipynb
?? dvc.lock
?? dvc.yaml

In [46]:
%%bash
git add .
git commit -m "Create DVC pipeline"

[experiments 2bdd8e7] Create DVC pipeline
 4 files changed, 378 insertions(+), 219 deletions(-)
 create mode 100644 dvc.lock
 create mode 100644 dvc.yaml

### Reproduce pipeline

In [47]:
!dvc repro split_dataset

'data/iris.csv.dvc' didn't change, skipping                           core>
Stage 'feature_extraction' didn't change, skipping
Stage 'split_dataset' didn't change, skipping
Data and pipelines are up to date.

## Collaborate on ML Experiments

### Specify remote storage (local ~ /tmp/dvc)

In [48]:
!dvc remote add -d local /tmp/dvc

Setting 'local' as a default remote.

### Push features to remote storage

In [49]:
!dvc push

  0% Uploading|                                      |0/6 [00:00<?,     ?file/s]
!
  0%|          |data/train.csv                 0.00/1.68k [00:00<?,       ?it/s]

  0%|          |data/test.csv                  0.00/1.14k [00:00<?,       ?it/s]


  0%|          |data/iris.csv                  0.00/2.78k [00:00<?,       ?it/s]



  0%|          |data/model.joblib                   0/897 [00:00<?,       ?it/s]




  0%|          |data/eval.txt                       0/124 [00:00<?,       ?it/s]



  0%|          |data/iris_featurized.csv       0.00/2.76k [00:00<?,       ?it/s]












6 files pushed

### Create tag `experiment-1`

In [50]:
!git tag -a experiment-1 -m "experiment-1"

### Checkout into your teammate experiment state

In [51]:
%%bash 

git checkout experiment-1
dvc checkout

M	.dvc/config
M	dvc-1-get-started.ipynb

Note: switching to 'experiment-1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD сейчас на 2bdd8e7 Create DVC pipeline

### Check Metrics

In [52]:
!dvc metrics show

Path           f1_score                                               core>
data/eval.txt  0.78618

### Reproduce experiment

In [53]:
# Nothing to reproduce
!dvc repro

'data/iris.csv.dvc' didn't change, skipping                           core>
Stage 'feature_extraction' didn't change, skipping
Stage 'split_dataset' didn't change, skipping
Stage 'train' didn't change, skipping
Stage 'evaluate' didn't change, skipping
Data and pipelines are up to date.

In [54]:
!dvc repro -f

Verifying data sources in stage: 'data/iris.csv.dvc'                  core>

Running stage 'feature_extraction':
> python src/featurization.py
                                                                      core>
Running stage 'split_dataset':
> python src/split_dataset.py --test_size 0.4
                                                                      core>
Running stage 'train':
> python src/train.py
                                                                      core>
Running stage 'evaluate':
> python src/evaluate.py
Use `dvc push` to send your updates to remote storage.                core>

In [55]:
# Check Metrics

!dvc metrics show

Path           f1_score                                               core>
data/eval.txt  0.78618